/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Election__factory } from "./Election__factory";
export { VoterRegistry__factory } from "./VoterRegistry__factory";
