/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace Election {
  export type CandidateStruct = {
    name: PromiseOrValue<string>;
    party: PromiseOrValue<string>;
    voteCount: PromiseOrValue<BigNumberish>;
  };

  export type CandidateStructOutput = [string, string, BigNumber] & {
    name: string;
    party: string;
    voteCount: BigNumber;
  };
}

export interface ElectionInterface extends utils.Interface {
  functions: {
    "addCandidate(uint256,string,string)": FunctionFragment;
    "admin()": FunctionFragment;
    "castVote(uint256,uint256,bytes32,bytes)": FunctionFragment;
    "createElection(string,uint256,uint256)": FunctionFragment;
    "electionCandidates(uint256,uint256)": FunctionFragment;
    "electionCount()": FunctionFragment;
    "elections(uint256)": FunctionFragment;
    "getCandidates(uint256)": FunctionFragment;
    "voterRegistry()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addCandidate"
      | "admin"
      | "castVote"
      | "createElection"
      | "electionCandidates"
      | "electionCount"
      | "elections"
      | "getCandidates"
      | "voterRegistry"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addCandidate",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createElection",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "electionCandidates",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "electionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "elections",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidates",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "voterRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "electionCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "electionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "elections", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voterRegistry",
    data: BytesLike
  ): Result;

  events: {
    "CandidateAdded(uint256,uint256,string)": EventFragment;
    "ElectionCreated(uint256,string)": EventFragment;
    "VoteCast(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CandidateAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ElectionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VoteCast"): EventFragment;
}

export interface CandidateAddedEventObject {
  electionId: BigNumber;
  candidateId: BigNumber;
  name: string;
}
export type CandidateAddedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  CandidateAddedEventObject
>;

export type CandidateAddedEventFilter = TypedEventFilter<CandidateAddedEvent>;

export interface ElectionCreatedEventObject {
  electionId: BigNumber;
  name: string;
}
export type ElectionCreatedEvent = TypedEvent<
  [BigNumber, string],
  ElectionCreatedEventObject
>;

export type ElectionCreatedEventFilter = TypedEventFilter<ElectionCreatedEvent>;

export interface VoteCastEventObject {
  electionId: BigNumber;
  candidateId: BigNumber;
}
export type VoteCastEvent = TypedEvent<
  [BigNumber, BigNumber],
  VoteCastEventObject
>;

export type VoteCastEventFilter = TypedEventFilter<VoteCastEvent>;

export interface Election extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ElectionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addCandidate(
      _electionId: PromiseOrValue<BigNumberish>,
      _name: PromiseOrValue<string>,
      _party: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    admin(overrides?: CallOverrides): Promise<[string]>;

    castVote(
      _electionId: PromiseOrValue<BigNumberish>,
      _candidateId: PromiseOrValue<BigNumberish>,
      _nullifier: PromiseOrValue<BytesLike>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createElection(
      _name: PromiseOrValue<string>,
      _start: PromiseOrValue<BigNumberish>,
      _end: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    electionCandidates(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber] & {
        name: string;
        party: string;
        voteCount: BigNumber;
      }
    >;

    electionCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    elections(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, boolean] & {
        name: string;
        startTime: BigNumber;
        endTime: BigNumber;
        isActive: boolean;
      }
    >;

    getCandidates(
      _electionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[Election.CandidateStructOutput[]]>;

    voterRegistry(overrides?: CallOverrides): Promise<[string]>;
  };

  addCandidate(
    _electionId: PromiseOrValue<BigNumberish>,
    _name: PromiseOrValue<string>,
    _party: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  admin(overrides?: CallOverrides): Promise<string>;

  castVote(
    _electionId: PromiseOrValue<BigNumberish>,
    _candidateId: PromiseOrValue<BigNumberish>,
    _nullifier: PromiseOrValue<BytesLike>,
    _signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createElection(
    _name: PromiseOrValue<string>,
    _start: PromiseOrValue<BigNumberish>,
    _end: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  electionCandidates(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber] & {
      name: string;
      party: string;
      voteCount: BigNumber;
    }
  >;

  electionCount(overrides?: CallOverrides): Promise<BigNumber>;

  elections(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, boolean] & {
      name: string;
      startTime: BigNumber;
      endTime: BigNumber;
      isActive: boolean;
    }
  >;

  getCandidates(
    _electionId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<Election.CandidateStructOutput[]>;

  voterRegistry(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addCandidate(
      _electionId: PromiseOrValue<BigNumberish>,
      _name: PromiseOrValue<string>,
      _party: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    admin(overrides?: CallOverrides): Promise<string>;

    castVote(
      _electionId: PromiseOrValue<BigNumberish>,
      _candidateId: PromiseOrValue<BigNumberish>,
      _nullifier: PromiseOrValue<BytesLike>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    createElection(
      _name: PromiseOrValue<string>,
      _start: PromiseOrValue<BigNumberish>,
      _end: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    electionCandidates(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber] & {
        name: string;
        party: string;
        voteCount: BigNumber;
      }
    >;

    electionCount(overrides?: CallOverrides): Promise<BigNumber>;

    elections(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, boolean] & {
        name: string;
        startTime: BigNumber;
        endTime: BigNumber;
        isActive: boolean;
      }
    >;

    getCandidates(
      _electionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<Election.CandidateStructOutput[]>;

    voterRegistry(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CandidateAdded(uint256,uint256,string)"(
      electionId?: PromiseOrValue<BigNumberish> | null,
      candidateId?: null,
      name?: null
    ): CandidateAddedEventFilter;
    CandidateAdded(
      electionId?: PromiseOrValue<BigNumberish> | null,
      candidateId?: null,
      name?: null
    ): CandidateAddedEventFilter;

    "ElectionCreated(uint256,string)"(
      electionId?: PromiseOrValue<BigNumberish> | null,
      name?: null
    ): ElectionCreatedEventFilter;
    ElectionCreated(
      electionId?: PromiseOrValue<BigNumberish> | null,
      name?: null
    ): ElectionCreatedEventFilter;

    "VoteCast(uint256,uint256)"(
      electionId?: PromiseOrValue<BigNumberish> | null,
      candidateId?: PromiseOrValue<BigNumberish> | null
    ): VoteCastEventFilter;
    VoteCast(
      electionId?: PromiseOrValue<BigNumberish> | null,
      candidateId?: PromiseOrValue<BigNumberish> | null
    ): VoteCastEventFilter;
  };

  estimateGas: {
    addCandidate(
      _electionId: PromiseOrValue<BigNumberish>,
      _name: PromiseOrValue<string>,
      _party: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<BigNumber>;

    castVote(
      _electionId: PromiseOrValue<BigNumberish>,
      _candidateId: PromiseOrValue<BigNumberish>,
      _nullifier: PromiseOrValue<BytesLike>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createElection(
      _name: PromiseOrValue<string>,
      _start: PromiseOrValue<BigNumberish>,
      _end: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    electionCandidates(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    electionCount(overrides?: CallOverrides): Promise<BigNumber>;

    elections(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCandidates(
      _electionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    voterRegistry(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addCandidate(
      _electionId: PromiseOrValue<BigNumberish>,
      _name: PromiseOrValue<string>,
      _party: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    castVote(
      _electionId: PromiseOrValue<BigNumberish>,
      _candidateId: PromiseOrValue<BigNumberish>,
      _nullifier: PromiseOrValue<BytesLike>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createElection(
      _name: PromiseOrValue<string>,
      _start: PromiseOrValue<BigNumberish>,
      _end: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    electionCandidates(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    electionCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    elections(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCandidates(
      _electionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    voterRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
