/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Election } from "./Election";
export type { VoterRegistry } from "./VoterRegistry";
export * as factories from "./factories";
export { Election__factory } from "./factories/Election__factory";
export { VoterRegistry__factory } from "./factories/VoterRegistry__factory";
