import { FormEvent, useEffect, useState } from 'react';
import { Activity, ArrowRight, BadgeCheck, Building2, CalendarDays, CheckCircle2, ChevronRight, CircleUserRound, Database, LogOut, MapPin, Menu, Plus, ShieldCheck, UsersRound, X } from 'lucide-react';
import { Candidate, createElection, createResource, Election, getCandidates, getCollection, getElections, getProfile, getVotingToken, Role, Session, storedSession, verifyIdentity } from './api';

type View = 'overview' | 'elections' | 'profile' | 'operations';
type Resource = 'constituencies' | 'polling-stations' | 'booths' | 'parties';

const roleCopy: Record<Role, { label: string; description: string }> = {
  VOTER: { label: 'Verified voter', description: 'Your ballot access and registration details' },
  ELECTION_OFFICER: { label: 'Election officer', description: 'Polling infrastructure and election readiness' },
  ADMIN: { label: 'Administrator', description: 'System-wide election operations' },
};

function App() {
  const [session, setSession] = useState<Session | null>(storedSession());
  const [view, setView] = useState<View>('overview');
  const [mobileNav, setMobileNav] = useState(false);

  if (!session) return <Login onLogin={setSession} />;
  const role = session.user.role;

  const signOut = () => {
    localStorage.removeItem('evote_session');
    setSession(null);
  };

  return (
    <div className="app-shell">
      <aside className={mobileNav ? 'sidebar sidebar-open' : 'sidebar'}>
        <div className="brand"><div className="brand-mark">e</div><div><strong>eVote</strong><span>civic ledger</span></div><button className="icon-button close-nav" onClick={() => setMobileNav(false)} aria-label="Close navigation"><X size={18} /></button></div>
        <div className="workspace-label">Workspace</div>
        <nav>
          <NavButton icon={<Activity size={18} />} label="Overview" active={view === 'overview'} onClick={() => { setView('overview'); setMobileNav(false); }} />
          <NavButton icon={<CalendarDays size={18} />} label="Elections" active={view === 'elections'} onClick={() => { setView('elections'); setMobileNav(false); }} />
          <NavButton icon={<CircleUserRound size={18} />} label="My profile" active={view === 'profile'} onClick={() => { setView('profile'); setMobileNav(false); }} />
          {role !== 'VOTER' && <NavButton icon={<Building2 size={18} />} label="Operations" active={view === 'operations'} onClick={() => { setView('operations'); setMobileNav(false); }} />}
        </nav>
        <div className="sidebar-footer"><div className="security-note"><ShieldCheck size={16} /><span>Identity verified<br /><small>Session protected</small></span></div><button className="sign-out" onClick={signOut}><LogOut size={16} /> Sign out</button></div>
      </aside>
      {mobileNav && <button className="mobile-scrim" onClick={() => setMobileNav(false)} aria-label="Close navigation" />}
      <main className="main-content">
        <header className="topbar"><button className="icon-button menu-button" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu size={20} /></button><div className="breadcrumbs">India / <strong>{view === 'overview' ? 'Overview' : view}</strong></div><div className="account-chip"><span className="avatar">{role[0]}</span><span>{roleCopy[role].label}</span></div></header>
        {view === 'overview' && <Overview session={session} onOpenElections={() => setView('elections')} />}
        {view === 'elections' && <Elections role={role} />}
        {view === 'profile' && <Profile />}
        {view === 'operations' && <Operations role={role} />}
      </main>
    </div>
  );
}

function Login({ onLogin }: { onLogin: (session: Session) => void }) {
  const [govtId, setGovtId] = useState('');
  const [name, setName] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setBusy(true); try { onLogin(await verifyIdentity(govtId, name)); } catch (e: any) { setError(e.response?.data?.error || 'Identity verification failed.'); } finally { setBusy(false); } };
  return <div className="login-page"><div className="login-visual"><div className="login-brand"><div className="brand-mark">e</div><strong>eVote</strong></div><div className="visual-copy"><p className="eyebrow">A clearer civic record</p><h1>One verified identity.<br /><em>One trusted vote.</em></h1><p>Secure access to your election workspace, registration details, and polling operations.</p></div><div className="visual-footer"><span>Polygon Amoy network</span><span>● System operational</span></div></div><div className="login-panel"><div className="login-form-wrap"><div className="mobile-login-brand"><div className="brand-mark">e</div><strong>eVote</strong></div><p className="eyebrow">Welcome back</p><h2>Verify your identity</h2><p className="muted">Use the government ID registered with your voter record.</p><form onSubmit={submit}><label>Government ID<input required value={govtId} onChange={(e) => setGovtId(e.target.value)} placeholder="EPIC or Aadhaar number" /></label><label>Full name<input required value={name} onChange={(e) => setName(e.target.value)} placeholder="As shown on your ID" /></label>{error && <div className="error-message">{error}</div>}<button className="primary-button full-width" disabled={busy}>{busy ? 'Verifying identity...' : <>Verify and continue <ArrowRight size={17} /></>}</button></form><div className="privacy-note"><ShieldCheck size={17} /><span>Your identity is hashed before it enters the voting flow.</span></div></div></div></div>;
}

function NavButton({ icon, label, active, onClick }: { icon: React.ReactNode; label: string; active: boolean; onClick: () => void }) { return <button className={active ? 'nav-button active' : 'nav-button'} onClick={onClick}>{icon}<span>{label}</span>{active && <ChevronRight size={15} />}</button>; }

function Overview({ session, onOpenElections }: { session: Session; onOpenElections: () => void }) {
  const [elections, setElections] = useState<Election[]>([]);
  useEffect(() => { getElections().then(setElections).catch(() => setElections([])); }, []);
  const role = session.user.role;
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">Friday, 18 September 2026</p><h1>Good morning.</h1><p className="muted">{roleCopy[role].description}.</p></div><div className="verified-pill"><BadgeCheck size={16} /> Verified session</div></div><section className="hero-panel"><div><p className="eyebrow light">Your civic workspace</p><h2>Participation, made tangible.</h2><p>Track active elections, confirm your registration, and keep every step accountable.</p><button className="light-button" onClick={onOpenElections}>View active elections <ArrowRight size={16} /></button></div><div className="hero-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="orbit-core"><ShieldCheck size={28} /><span>SECURE</span></div></div></section><div className="stat-grid"><Stat icon={<CalendarDays />} label="Active elections" value={String(elections.length).padStart(2, '0')} accent="teal" /><Stat icon={<CheckCircle2 />} label="Identity status" value={session.user.isVerified ? 'Verified' : 'Pending'} accent="green" /><Stat icon={<Database />} label="Ledger network" value="Amoy" accent="yellow" /></div><section className="section-heading"><div><p className="eyebrow">Live now</p><h2>Active elections</h2></div><button className="text-button" onClick={onOpenElections}>See all <ArrowRight size={15} /></button></section><div className="election-list">{elections.slice(0, 3).map((election) => <ElectionRow key={election._id} election={election} />)}{elections.length === 0 && <EmptyState text="No active elections are available right now." />}</div></div>;
}

function Stat({ icon, label, value, accent }: { icon: React.ReactNode; label: string; value: string; accent: string }) { return <div className={`stat-card ${accent}`}><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>; }
function ElectionRow({ election }: { election: Election }) { return <div className="election-row"><div className="date-tile"><CalendarDays size={17} /><span>{election.startTime ? new Date(election.startTime).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : 'OPEN'}</span></div><div className="election-main"><strong>{election.name}</strong><span>{election.constituencyId ? `Constituency ${election.constituencyId}` : 'National election'} · Active</span></div><span className="status-dot">Live</span><ChevronRight size={18} className="row-arrow" /></div>; }
function EmptyState({ text }: { text: string }) { return <div className="empty-state"><CalendarDays size={22} /><span>{text}</span></div>; }

function Elections({ role }: { role: Role }) {
  const [elections, setElections] = useState<Election[]>([]); const [selected, setSelected] = useState<Election | null>(null); const [candidates, setCandidates] = useState<Candidate[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [voting, setVoting] = useState(false);
  useEffect(() => { getElections().then(setElections).finally(() => setLoading(false)); }, []);
  const openElection = async (election: Election) => { setSelected(election); setMessage(''); setCandidates(await getCandidates(election._id).catch(() => [])); };
  const requestToken = async (candidate: Candidate) => { setVoting(true); try { const result = await getVotingToken(selected!._id, `${selected?._id}:${candidate.blockchainCandidateId}:${Date.now()}`); setMessage(`Token issued for ${result.blockchainNetwork} (chain ${result.chainId}), contract ${result.contractAddress}. Blockchain submission remains a simulation in this backend.`); } catch (e: any) { setMessage(e.response?.data?.error || 'Could not issue a voting token.'); } finally { setVoting(false); } };
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">Election center</p><h1>Active elections</h1><p className="muted">Choose an election to inspect its candidates and voting status.</p></div>{role !== 'VOTER' && <span className="role-badge"><ShieldCheck size={14} /> {roleCopy[role].label}</span>}</div>{message && <div className="success-banner"><CheckCircle2 size={18} />{message}</div>}<div className="election-layout"><div className="election-list large">{loading ? <div className="loading">Loading elections...</div> : elections.length ? elections.map((election) => <button className={selected?._id === election._id ? 'election-row selected' : 'election-row'} key={election._id} onClick={() => openElection(election)}><div className="date-tile"><CalendarDays size={17} /><span>{election.startTime ? new Date(election.startTime).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : 'OPEN'}</span></div><div className="election-main"><strong>{election.name}</strong><span>{election.blockchainNetwork || 'Configured network'} · Chain {election.chainId ?? 'n/a'} · Election {election.blockchainId ?? 'n/a'}</span></div><span className="status-dot">Live</span><ChevronRight size={18} className="row-arrow" /></button>) : <EmptyState text="No active elections are available." />}</div>{selected && <div className="detail-panel"><div className="detail-top"><div className="detail-icon"><CalendarDays size={23} /></div><div><p className="eyebrow">Selected election</p><h2>{selected.name}</h2></div></div><div className="detail-meta"><span><MapPin size={15} /> {selected.constituencyId || 'National constituency'}</span><span><Activity size={15} /> {selected.blockchainNetwork || 'Configured network'} · Chain {selected.chainId ?? 'n/a'}</span><span><Database size={15} /> Contract {selected.contractAddress || 'Not configured'}</span></div><h3>Candidates</h3>{candidates.length ? candidates.map((candidate) => <div className="candidate-row" key={candidate._id}><div className="candidate-avatar">{candidate.name[0]}</div><div><strong>{candidate.name}</strong><span>{candidate.party || 'Independent'}</span></div>{role === 'VOTER' && <button className="small-button" disabled={voting} onClick={() => requestToken(candidate)}>Select</button>}</div>) : <p className="muted">No candidates found for this election.</p>}{role === 'VOTER' && candidates.length > 0 && <p className="fine-print">Selection requests a signed voting token for this election's configured chain.</p>}</div>}</div></div>;
}

function Profile() { const [profile, setProfile] = useState<any>(null); const [error, setError] = useState(''); useEffect(() => { getProfile().then(setProfile).catch((e) => setError(e.response?.data?.error || 'Profile unavailable.')); }, []); return <div className="page narrow-page"><div className="page-heading"><div><p className="eyebrow">Verified record</p><h1>My profile</h1><p className="muted">Your registration details are shown with sensitive identifiers masked.</p></div></div>{error ? <div className="error-message">{error}</div> : !profile ? <div className="loading">Loading profile...</div> : <div className="profile-card"><div className="profile-header"><div className="profile-avatar"><CircleUserRound size={28} /></div><div><h2>{profile.nationalId ? `Voter ${profile.nationalId.slice(-4)}` : 'Verified voter'}</h2><span className="status-text"><CheckCircle2 size={15} /> Identity verified</span></div></div><div className="profile-grid"><Info label="Date of birth" value={profile.dob ? new Date(profile.dob).toLocaleDateString() : 'Not available'} /><Info label="Gender" value={profile.gender || 'Not available'} /><Info label="Constituency" value={profile.constituencyId?.name || 'Not assigned'} /><Info label="Polling station" value={profile.stationId?.name || 'Not assigned'} /><Info label="Station address" value={profile.stationId?.address || 'Not assigned'} /><Info label="Booth number" value={profile.boothId?.boothNumber ? `Booth ${profile.boothId.boothNumber}` : 'Not assigned'} /></div></div>}</div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="info-field"><span>{label}</span><strong>{value}</strong></div>; }

function Operations({ role }: { role: Role }) { const resources: { key: Resource; label: string; icon: React.ReactNode; allowed: Role[] }[] = [{ key: 'constituencies', label: 'Constituencies', icon: <MapPin />, allowed: ['ADMIN'] }, { key: 'polling-stations', label: 'Polling stations', icon: <Building2 />, allowed: ['ADMIN', 'ELECTION_OFFICER'] }, { key: 'booths', label: 'Booths', icon: <UsersRound />, allowed: ['ADMIN', 'ELECTION_OFFICER'] }, { key: 'parties', label: 'Political parties', icon: <ShieldCheck />, allowed: ['ADMIN'] }]; const available = resources.filter((item) => item.allowed.includes(role)); const [resource, setResource] = useState<Resource>(available[0].key); return <div className="page"><div className="page-heading"><div><p className="eyebrow">Operations desk</p><h1>Manage the system</h1><p className="muted">Create and review the records available to your role.</p></div></div><div className="operations-tabs">{available.map((item) => <button className={resource === item.key ? 'operation-tab active' : 'operation-tab'} key={item.key} onClick={() => setResource(item.key)}>{item.icon}<span>{item.label}</span></button>)}</div><ResourceManager resource={resource} /><ElectionCreator role={role} /></div>; }

function ResourceManager({ resource }: { resource: Resource }) { const [items, setItems] = useState<any[]>([]); const [form, setForm] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const configs: Record<Resource, { fields: string[]; labels: string[] }> = { constituencies: { fields: ['name', 'code', 'region'], labels: ['Name', 'Code', 'Region'] }, 'polling-stations': { fields: ['name', 'address', 'constituencyId'], labels: ['Name', 'Address', 'Constituency ID'] }, booths: { fields: ['boothNumber', 'stationId', 'capacity'], labels: ['Booth number', 'Station ID', 'Capacity'] }, parties: { fields: ['name', 'abbreviation', 'logoUrl'], labels: ['Name', 'Abbreviation', 'Logo URL'] } }; const config = configs[resource]; const load = () => getCollection(resource).then(setItems).catch(() => setItems([])); useEffect(() => { load(); }, [resource]); const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); const payload = { ...form, ...(resource === 'booths' ? { boothNumber: Number(form.boothNumber), capacity: Number(form.capacity) } : {}) }; await createResource(resource, payload).then(() => { setForm({}); load(); }).finally(() => setBusy(false)); }; return <section className="operation-section"><div className="section-heading"><div><p className="eyebrow">{resource.replace('-', ' ')}</p><h2>Records</h2></div><span className="count-badge">{items.length} total</span></div><form className="inline-form" onSubmit={submit}>{config.fields.map((field, i) => <input required key={field} value={form[field] || ''} onChange={(e) => setForm({ ...form, [field]: e.target.value })} placeholder={config.labels[i]} />)}<button className="primary-button" disabled={busy}><Plus size={16} /> Create</button></form><div className="records-list">{items.map((item) => <div className="record-row" key={item._id}><strong>{item.name || `Booth ${item.boothNumber}`}</strong><span>{item.code || item.address || item.abbreviation || `Capacity ${item.capacity || 'n/a'}`}</span></div>)}{!items.length && <p className="muted">No records found yet.</p>}</div></section>; }
function ElectionCreator({ role }: { role: Role }) { const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', startTime: '', endTime: '', blockchainId: '', chainId: '80002', blockchainNetwork: 'polygon-amoy', contractAddress: '', constituencyId: '' }); const [message, setMessage] = useState(''); if (role === 'VOTER') return null; return <section className="operation-section election-creator"><div className="section-heading"><div><p className="eyebrow">Election setup</p><h2>Create an election</h2></div><button className="text-button" onClick={() => setOpen(!open)}>{open ? 'Close' : 'Open form'} <ChevronRight size={15} /></button></div>{open && <form className="create-election-form" onSubmit={async (event) => { event.preventDefault(); await createElection({ ...form, blockchainId: Number(form.blockchainId), chainId: Number(form.chainId) }); setMessage('Election created with its own chain routing and is now active or scheduled.'); setOpen(false); }}><input required placeholder="Election name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input required type="datetime-local" value={form.startTime} onChange={(e) => setForm({ ...form, startTime: e.target.value })} /><input required type="datetime-local" value={form.endTime} onChange={(e) => setForm({ ...form, endTime: e.target.value })} /><input required type="number" placeholder="On-chain election ID" value={form.blockchainId} onChange={(e) => setForm({ ...form, blockchainId: e.target.value })} /><input required type="number" placeholder="Network chain ID" value={form.chainId} onChange={(e) => setForm({ ...form, chainId: e.target.value })} /><input required placeholder="Network name, e.g. polygon-amoy" value={form.blockchainNetwork} onChange={(e) => setForm({ ...form, blockchainNetwork: e.target.value })} /><input required placeholder="Election contract address" value={form.contractAddress} onChange={(e) => setForm({ ...form, contractAddress: e.target.value })} /><input required placeholder="Constituency ID" value={form.constituencyId} onChange={(e) => setForm({ ...form, constituencyId: e.target.value })} /><button className="primary-button" type="submit"><Plus size={16} /> Create election</button></form>}{message && <div className="success-banner"><CheckCircle2 size={17} /> {message}</div>}</section>; }

export default App;
