const STAGES = [
  'General',
  'Ingestion',
  'Analysis',
  'Design',
  'Implementation',
  'Testing',
  'QA/UAT',
  'Production',
  'Completed',
];

const INITIAL_RESOURCES = [
  {
    id: 1,
    name: 'Avery Chen',
    email: 'avery.chen@example.com',
    role: 'Contributor',
  },
  {
    id: 2,
    name: 'Priya Nair',
    email: 'priya.nair@example.com',
    role: 'Contributor',
  },
  {
    id: 3,
    name: 'Mateo Silva',
    email: 'mateo.silva@example.com',
    role: 'Contributor',
  },
  {
    id: 4,
    name: 'Jordan Lee',
    email: 'jordan.lee@example.com',
    role: 'Contributor',
  },
  {
    id: 5,
    name: 'Nina Patel',
    email: 'nina.patel@example.com',
    role: 'Contributor',
  },
  {
    id: 6,
    name: 'Ram Mohan Yaratapally',
    email: 'ram.mohan.yaratapally@oracle.com',
    role: 'Manager',
  },
];

const INITIAL_TASKS = [
  {
    id: 101,
    title: 'SSO onboarding flow',
    status: 'Implementation',
    effort: 20,
    start: '2026-04-13',
    end: '2026-04-19',
    assignee: 'Avery Chen',
    squad: 'Platform',
    release: '24.4',
    milestone: false,
    priority: 'High',
    blocked: false,
    bugUrl: 'https://jira.example.com/browse/SPRINT-101',
    comments: [
      {
        id: 1001,
        text: 'Frontend screens approved. Waiting on final callback URL from IT.',
        createdAt: '2026-04-17T08:10:00.000Z',
      },
      {
        id: 1002,
        text: 'Redirect URI list reviewed with the security team.',
        createdAt: '2026-04-16T10:25:00.000Z',
      },
    ],
    draftComment: '',
  },
  {
    id: 102,
    title: 'Burndown dashboard refresh',
    status: 'Analysis',
    effort: 12,
    start: '2026-04-15',
    end: '2026-04-18',
    assignee: 'Priya Nair',
    squad: 'Insights',
    release: '24.4',
    milestone: false,
    priority: 'Medium',
    blocked: false,
    bugUrl: '',
    comments: [
      {
        id: 1003,
        text: 'Need confirmation on KPI definitions before design starts.',
        createdAt: '2026-04-17T05:00:00.000Z',
      },
    ],
    draftComment: '',
  },
  {
    id: 103,
    title: 'Mobile navigation QA sweep',
    status: 'Testing',
    effort: 8,
    start: '2026-04-16',
    end: '2026-04-18',
    assignee: 'Jordan Lee',
    squad: 'Web',
    release: '24.4',
    milestone: false,
    priority: 'High',
    blocked: true,
    bugUrl: 'https://jira.example.com/browse/SPRINT-203',
    comments: [
      {
        id: 1004,
        text: 'Android 13 regression still open on the profile menu.',
        createdAt: '2026-04-17T07:40:00.000Z',
      },
      {
        id: 1005,
        text: 'iOS results are clear after the latest patch.',
        createdAt: '2026-04-16T15:20:00.000Z',
      },
    ],
    draftComment: '',
  },
  {
    id: 104,
    title: 'Release notes for sprint 18',
    status: 'QA/UAT',
    effort: 5,
    start: '2026-04-17',
    end: '2026-04-19',
    assignee: 'Nina Patel',
    squad: 'PMO',
    release: '24.4',
    milestone: false,
    priority: 'Low',
    blocked: false,
    bugUrl: '',
    comments: [
      {
        id: 1006,
        text: 'Draft reviewed by stakeholders. Final screenshots still pending.',
        createdAt: '2026-04-17T09:30:00.000Z',
      },
    ],
    draftComment: '',
  },
  {
    id: 105,
    title: 'Alert routing cleanup',
    status: 'Production',
    effort: 9,
    start: '2026-04-10',
    end: '2026-04-14',
    assignee: 'Mateo Silva',
    squad: 'SRE',
    release: '24.3',
    milestone: true,
    priority: 'Medium',
    blocked: false,
    bugUrl: 'https://jira.example.com/browse/OPS-77',
    comments: [
      {
        id: 1007,
        text: 'Rolled out successfully with no incidents in the last 48 hours.',
        createdAt: '2026-04-15T11:30:00.000Z',
      },
    ],
    draftComment: '',
  },
  {
    id: 106,
    title: 'Customer import validation',
    status: 'Design',
    effort: 13,
    start: '2026-04-14',
    end: '2026-04-21',
    assignee: 'Priya Nair',
    squad: 'Data',
    release: '24.5',
    milestone: false,
    priority: 'High',
    blocked: false,
    bugUrl: '',
    comments: [
      {
        id: 1008,
        text: 'Error state copy ready. Edge-case mapping session scheduled tomorrow.',
        createdAt: '2026-04-17T06:00:00.000Z',
      },
      {
        id: 1009,
        text: 'Validation rules aligned with the import team.',
        createdAt: '2026-04-16T04:00:00.000Z',
      },
    ],
    draftComment: '',
  },
  {
    id: 107,
    title: 'New workspace request intake',
    status: 'Ingestion',
    effort: 3,
    start: '2026-04-17',
    end: '2026-04-17',
    assignee: 'Nina Patel',
    squad: 'Operations',
    release: '24.4',
    milestone: false,
    priority: 'Low',
    blocked: false,
    bugUrl: '',
    comments: [
      {
        id: 1010,
        text: 'Ticket received from support; triage during standup.',
        createdAt: '2026-04-17T03:20:00.000Z',
      },
    ],
    draftComment: '',
  },
];

module.exports = {
  INITIAL_RESOURCES,
  INITIAL_TASKS,
  STAGES,
};
